/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sa.cobacoba.tambah;

import java.awt.Color;
import javax.swing.JPanel;


public class TambahWindow extends javax.swing.JFrame {

    private final JPanel barangPanel;
    private final JPanel langgananPanel;
    private final JPanel suppPanel;
    private final JPanel salesPanel;
    private java.sql.Connection cons;
    
    public TambahWindow(java.sql.Connection conn) {
        salesPanel = new TambahSalesPanel(conn);
        suppPanel = new TambahSuppPanel(conn);
        langgananPanel = new TambahLanggananPanel(conn);
        barangPanel = new TambahBarangPanel(conn);
        cons = conn;
        initComponents();
        containerPanel.add(barangPanel, java.awt.BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        langgananButton = new javax.swing.JButton();
        barangButton = new javax.swing.JButton();
        salesButton = new javax.swing.JButton();
        suppButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        containerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setName("TambahWindow"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(780, 444));
        jPanel1.setName("panelTambah"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 444));

        langgananButton.setBackground(new java.awt.Color(102, 102, 102));
        langgananButton.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        langgananButton.setText("Langganan");
        langgananButton.setBorder(null);
        langgananButton.setBorderPainted(false);
        langgananButton.setFocusable(false);
        langgananButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        langgananButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                langgananButtonActionPerformed(evt);
            }
        });

        barangButton.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        barangButton.setText("Barang");
        barangButton.setBorder(null);
        barangButton.setBorderPainted(false);
        barangButton.setFocusable(false);
        barangButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangButtonActionPerformed(evt);
            }
        });

        salesButton.setBackground(new java.awt.Color(102, 102, 102));
        salesButton.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        salesButton.setText("Salesman");
        salesButton.setBorder(null);
        salesButton.setBorderPainted(false);
        salesButton.setFocusable(false);
        salesButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesButtonActionPerformed(evt);
            }
        });

        suppButton.setBackground(new java.awt.Color(102, 102, 102));
        suppButton.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        suppButton.setText("Supplier");
        suppButton.setBorder(null);
        suppButton.setBorderPainted(false);
        suppButton.setFocusable(false);
        suppButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Tambah");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        backButton.setBackground(new java.awt.Color(102, 102, 102));
        backButton.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        backButton.setText("Back");
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setFocusable(false);
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(langgananButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(barangButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(salesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(suppButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(barangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(suppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(langgananButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(salesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);
        jPanel3.getAccessibleContext().setAccessibleName("");
        jPanel3.getAccessibleContext().setAccessibleDescription("");

        containerPanel.setBackground(new java.awt.Color(51, 51, 51));
        containerPanel.setLayout(new java.awt.BorderLayout());
        jPanel1.add(containerPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void langgananButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_langgananButtonActionPerformed
        barangButton.setBackground(new Color(102, 102, 102));
        langgananButton.setBackground(new Color(255, 255, 255));
        suppButton.setBackground(new Color(102, 102, 102));
        salesButton.setBackground(new Color(102, 102, 102));
        containerPanel.removeAll();
        containerPanel.add(langgananPanel, java.awt.BorderLayout.CENTER);
        containerPanel.revalidate();
        containerPanel.repaint();
    }//GEN-LAST:event_langgananButtonActionPerformed

    private void barangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangButtonActionPerformed
        barangButton.setBackground(new Color(255, 255, 255));
        langgananButton.setBackground(new Color(102, 102, 102));
        suppButton.setBackground(new Color(102, 102, 102));
        salesButton.setBackground(new Color(102, 102, 102));
        containerPanel.removeAll();
        containerPanel.add(barangPanel, java.awt.BorderLayout.CENTER);
        containerPanel.revalidate();
        containerPanel.repaint();
    }//GEN-LAST:event_barangButtonActionPerformed

    private void salesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesButtonActionPerformed
        barangButton.setBackground(new Color(102, 102, 102));
        langgananButton.setBackground(new Color(102, 102, 102));
        suppButton.setBackground(new Color(102, 102, 102));
        salesButton.setBackground(new Color(255, 255, 255));
        containerPanel.removeAll();
        containerPanel.add(salesPanel, java.awt.BorderLayout.CENTER);
        containerPanel.revalidate();
        containerPanel.repaint();
    }//GEN-LAST:event_salesButtonActionPerformed

    private void suppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppButtonActionPerformed
        barangButton.setBackground(new Color(102, 102, 102));
        langgananButton.setBackground(new Color(102, 102, 102));
        suppButton.setBackground(new Color(255, 255, 255));
        salesButton.setBackground(new Color(102, 102, 102));
        containerPanel.removeAll();
        containerPanel.add(suppPanel, java.awt.BorderLayout.CENTER);
        containerPanel.revalidate();
        containerPanel.repaint();
    }//GEN-LAST:event_suppButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        try {
            cons.close();
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        new com.sa.cobacoba.MainWindow().setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton barangButton;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton langgananButton;
    private javax.swing.JButton salesButton;
    private javax.swing.JButton suppButton;
    // End of variables declaration//GEN-END:variables
}
