/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sa.cobacoba.pelunasan;

public class PelunasanWindow extends javax.swing.JFrame {

    java.sql.Connection cons;
    public PelunasanWindow(java.sql.Connection conn) {
        cons = conn;
        initComponents();
        
        PelunasanUtang lunas = new PelunasanUtang(cons, this);
        jPanel1.add(lunas, java.awt.BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        utangMenu = new javax.swing.JMenu();
        piutangMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 476));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 476));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jMenuBar1.setPreferredSize(new java.awt.Dimension(75, 30));

        utangMenu.setLabel("Utang");
        utangMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                utangMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(utangMenu);

        piutangMenu.setLabel("Piutang");
        piutangMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piutangMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(piutangMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void piutangMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piutangMenuMouseClicked
        PelunasanPiutang lunas = new PelunasanPiutang(cons, this);
        jPanel1.removeAll();
        jPanel1.add(lunas, java.awt.BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_piutangMenuMouseClicked

    private void utangMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_utangMenuMouseClicked
        PelunasanUtang lunas = new PelunasanUtang(cons, this);
        jPanel1.removeAll();
        jPanel1.add(lunas, java.awt.BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_utangMenuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu piutangMenu;
    private javax.swing.JMenu utangMenu;
    // End of variables declaration//GEN-END:variables
}
