/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sa.cobacoba.lihat;

import com.sa.cobacoba.functions.GeneralFunction;

public class LihatUtangPerLangganan extends javax.swing.JPanel {

    java.sql.Connection cons;
    /**
     * Creates new form LihatUtangPerLangganan
     * @param conn for connection
     */
    public LihatUtangPerLangganan(java.sql.Connection conn) {
        cons = conn;
        initComponents();
        addNamaSupp();
    }
    
    private void addNamaSupp() {
        try (java.sql.Statement stmt = cons.createStatement()) {
            java.sql.ResultSet resultSet = stmt.executeQuery("SELECT nama_client, kota_client FROM client ORDER BY nama_client");
            while (resultSet.next()) {
                String nama = resultSet.getString("nama_client");
                String kota = resultSet.getString("kota_client");
                if (kota != null) {
                    nama = nama.concat("/");
                    nama = nama.concat(resultSet.getString("kota_client"));
                }
                namaSupp.addItem(nama);
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error querying nama_supplier", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        } finally {
            namaSupp.setSelectedIndex(-1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namaSupp = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(1350, 665));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 130));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Supplier");

        namaSupp.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        searchButton.setBackground(new java.awt.Color(102, 102, 102));
        searchButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namaSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(896, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor Nota", "Tanggal Nota", "Nilai Nota", "Lunas Nota", "Tanggal Lunas", "Saldo Nota"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        javax.swing.table.DefaultTableModel tblModel = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        if (tblModel.getRowCount() != 0) {
            tblModel.setRowCount(0);
        }
        
        String namaSupplierString;
        try {
            namaSupplierString = namaSupp.getSelectedItem().toString();
        } catch (java.lang.NullPointerException e) {
            return;
        }
        
        
        // get id client
        String namaCli = null, kotaCli;
        String query;
        try (java.util.Scanner scanner = new java.util.Scanner(namaSupplierString))
        {
            scanner.useDelimiter("/");
            namaCli = scanner.next();
            kotaCli = scanner.next();
            
            if (kotaCli == null)
                throw new java.util.NoSuchElementException();
            
        } catch (java.util.NoSuchElementException e) {
            kotaCli = null;
        }
        
        int idClient = 0;
        if (kotaCli == null) {
            query = "SELECT id FROM client WHERE nama_client = ? AND kota_client IS NULL";
            try (java.sql.PreparedStatement stmt = cons.prepareStatement(query))
            {
                stmt.setString(1, namaCli);
                java.sql.ResultSet resultSet = stmt.executeQuery();
                while (resultSet.next()) {
                    idClient = resultSet.getInt("id");
                }
            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            query = "SELECT id FROM client WHERE nama_client = ? AND kota_client = ?";
            try (java.sql.PreparedStatement stmt = cons.prepareStatement(query))
            {
                stmt.setString(1, namaCli);
                stmt.setString(2, kotaCli);
                java.sql.ResultSet resultSet = stmt.executeQuery();
                while (resultSet.next()) {
                    idClient = resultSet.getInt("id");
                }
            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }

        
        long totalNilaiNota = 0, totalLunasNota = 0;
        boolean adaPelunasan = false;
        try (java.sql.PreparedStatement stmt = cons.prepareStatement("SELECT nomor_nota, tanggal_nota, nilai_nota "
                + "FROM bnota WHERE id_client = ? "
                + "ORDER BY tanggal_nota"))
        {
            stmt.setInt(1, idClient);
            java.sql.ResultSet resultSet = stmt.executeQuery();
            while (resultSet.next()) {
                String nomor_nota = resultSet.getString("nomor_nota");
                String tanggal_nota = GeneralFunction.sqlDate2String(resultSet.getDate("tanggal_nota"));
                int nilaiNotaInt = resultSet.getInt("nilai_nota");
                totalNilaiNota += (long) nilaiNotaInt;
                String nilai_nota = String.format("%,d", nilaiNotaInt);
                int saldoNotaInt = nilaiNotaInt;
                adaPelunasan = false;
                
                try (java.sql.PreparedStatement stmt2 = cons.prepareStatement("SELECT tanggal_lunas, lunas_nota "
                        + "FROM blunas WHERE id_client = ? AND nomor_nota = ? "
                        + "ORDER BY tanggal_lunas"))
                {
                    stmt2.setInt(1, idClient);
                    stmt2.setString(2, nomor_nota);
                    java.sql.ResultSet result = stmt2.executeQuery();
                    while (result.next()) {
                        
                        adaPelunasan = true;
                        String tanggal_lunas = GeneralFunction.sqlDate2String(result.getDate("tanggal_lunas"));
                        int lunasNotaInt = result.getInt("lunas_nota");
                        totalLunasNota += (long) lunasNotaInt;
                        String lunas_nota = String.format("%,d", lunasNotaInt);
                        saldoNotaInt -= lunasNotaInt;
                        
                        String[] row = {
                            nomor_nota,
                            tanggal_nota,
                            nilai_nota,
                            lunas_nota,
                            tanggal_lunas,
                            String.valueOf(saldoNotaInt)
                        };
                        
                        tblModel.addRow(row);
                    }
                    
                    if (!adaPelunasan) {
                        String[] row = {
                            nomor_nota,
                            tanggal_nota,
                            nilai_nota,
                            "0",
                            "",
                            nilai_nota
                        };
                        tblModel.addRow(row);
                    }
                    
                    String[] row = {"","","","","",""};
                    tblModel.addRow(row);
                }
                
            }
            
            long saldoNotaTerakhir = totalNilaiNota - totalLunasNota;
            String[] row = {"TOTAL", "", String.format("%,d", totalNilaiNota), String.format("%,d", totalLunasNota), 
                            "", String.format("%,d", saldoNotaTerakhir)};
            
            tblModel.addRow(row);
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> namaSupp;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
