/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sa.cobacoba.beli;

import com.sa.cobacoba.functions.GeneralFunction;

public class Beli extends javax.swing.JFrame {
    
    java.sql.Connection cons;
    public Beli(java.sql.Connection conn) {
        cons = conn;
        initComponents();
        dataPanel.setVisible(false);
        peringatan.setVisible(false);
        setComboBox();
        setTodayDate();
    }
    
    private void setComboBox() {
        try (java.sql.Statement stmt = cons.createStatement()){
            java.sql.ResultSet resultSet = stmt.executeQuery("SELECT nama_client, kota_client FROM client ORDER BY nama_client");
            while (resultSet.next()) {
                String nama = resultSet.getString("nama_client");
                String kota = resultSet.getString("kota_client");
                if (kota != null) {
                    nama = nama.concat("/");
                    nama = nama.concat(kota);
                }
                namaSupp.addItem(nama);
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error querying database", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        } finally {
            namaSupp.setSelectedIndex(-1);
        }
    }
    
    private void setTodayDate() {
        java.time.LocalDate today = java.time.LocalDate.now();
        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String formattedDate = today.format(formatter);
        tanggalNota.addItem(formattedDate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namaSupp = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        nomorNota = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tanggalNota = new javax.swing.JComboBox<>();
        dataPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        namaBarang = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        hargaBeli = new javax.swing.JTextField();
        hargaJual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        peringatan = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBeli = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        totalHarga = new javax.swing.JTextField();
        beliButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 500));
        setSize(new java.awt.Dimension(950, 500));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 476));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 661));
        jPanel1.setLayout(new java.awt.BorderLayout());

        sidebarPanel.setBackground(new java.awt.Color(102, 102, 102));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(200, 476));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Beli Barang");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Supplier");

        namaSupp.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        namaSupp.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nomor Nota");

        nomorNota.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Nota");

        backButton.setBackground(new java.awt.Color(51, 51, 51));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        submitButton.setBackground(new java.awt.Color(51, 51, 51));
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.setBorder(null);
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("dd-MM-yyyy");

        tanggalNota.setEditable(true);
        tanggalNota.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(namaSupp, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nomorNota, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(tanggalNota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomorNota, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggalNota, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(8, 8, 8)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 103, Short.MAX_VALUE))
        );

        jPanel1.add(sidebarPanel, java.awt.BorderLayout.WEST);

        dataPanel.setBackground(new java.awt.Color(102, 102, 102));
        dataPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setPreferredSize(new java.awt.Dimension(630, 150));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Barang");

        namaBarang.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        namaBarang.setToolTipText("");
        namaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaBarangActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga Beli");

        hargaBeli.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        hargaJual.setEditable(false);
        hargaJual.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Harga Jual");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jumlah");

        jumlah.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });

        peringatan.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        peringatan.setForeground(new java.awt.Color(255, 0, 0));
        peringatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        peringatan.setText("jLabel9");

        addButton.setBackground(new java.awt.Color(51, 51, 51));
        addButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add");
        addButton.setBorder(null);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(51, 51, 51));
        updateButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.setBorder(null);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(51, 51, 51));
        deleteButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete");
        deleteButton.setBorder(null);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(peringatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(hargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(hargaJual)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(namaBarang)
                        .addComponent(hargaBeli))
                    .addComponent(jumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(peringatan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dataPanel.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        tableBeli.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        tableBeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Harga Beli", "Harga Jual", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBeli.setRowHeight(25);
        tableBeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBeliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBeli);

        dataPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(630, 109));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Harga");

        harga.setEditable(false);
        harga.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        harga.setText("0");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Diskon");

        diskon.setText("0");
        diskon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                diskonKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Harga");

        totalHarga.setEditable(false);
        totalHarga.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        totalHarga.setText("0");

        beliButton.setBackground(new java.awt.Color(102, 102, 102));
        beliButton.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        beliButton.setForeground(new java.awt.Color(255, 255, 255));
        beliButton.setBorder(null);
        beliButton.setLabel("Beli >>");
        beliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diskon, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(totalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(beliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(harga, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(diskon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(beliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        dataPanel.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(dataPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        try {
            cons.close();
        } catch (java.sql.SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        new com.sa.cobacoba.MainWindow().setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        boolean salah = validateAll();
        if (!salah) {
            dataPanel.setVisible(true);
            namaSupp.setEditable(false);
            namaSupp.setEnabled(false);
            nomorNota.setEditable(false);
            nomorNota.setEnabled(false);
            tanggalNota.setEditable(false);
            tanggalNota.setEnabled(false);
            submitButton.setEnabled(false);
            
            getNamaBarang();
            hargaBeli.setText("");
            hargaJual.setText("");
        }
    }//GEN-LAST:event_submitButtonActionPerformed
    
    private boolean validateAll() {
        try {
            if (namaSupp.getSelectedItem() == null) {
                throw new java.lang.NullPointerException("Nama supplier tidak boleh kosong");
            }

            if (namaSupp.getSelectedItem().toString().isEmpty()) {
                throw new java.lang.NullPointerException("Nama supplier tidak boleh kosong");
            }

            if (nomorNota.getText().isEmpty()) {
                throw new java.lang.NullPointerException("Nomor nota tidak boleh kosong");
            }

            if (tanggalNota.getSelectedItem().toString().isEmpty()) {
                throw new java.lang.NullPointerException("Tanggal nota tidak boleh kosong");
            }
        } catch (java.lang.NullPointerException e){
            return true;
        }
            
        return false;
    }
    
    private void getNamaBarang() {
        try (java.sql.Statement stmt = cons.createStatement()) {
            java.sql.ResultSet resultSet = stmt.executeQuery("SELECT nama_barang FROM stock ORDER BY nama_barang");
            while (resultSet.next()) {
                namaBarang.addItem(resultSet.getString("nama_barang"));
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error querying nama_barang in database", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        } finally {
            namaBarang.setSelectedIndex(-1);
        }
    }
    
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        boolean salah = validateForm();
        if (!salah) {
            javax.swing.table.DefaultTableModel tblModel = (javax.swing.table.DefaultTableModel) tableBeli.getModel();
            if (tableBeli.getSelectedRowCount() == 1) {
                tblModel.setValueAt(namaBarang.getSelectedItem().toString(), tableBeli.getSelectedRow(), 0);
                tblModel.setValueAt(hargaBeli.getText(), tableBeli.getSelectedRow(), 1);
                tblModel.setValueAt(hargaJual.getText(), tableBeli.getSelectedRow(), 2);
                tblModel.setValueAt(jumlah.getText(), tableBeli.getSelectedRow(), 3);
                
                namaBarang.setSelectedIndex(-1);
                hargaBeli.setText("");
                hargaJual.setText("");
                jumlah.setText("");
                
                updateHarga();
                javax.swing.JOptionPane.showMessageDialog(null, "SUCCESS UPDATING", "SUCCESS", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Choose one row to update", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        javax.swing.table.DefaultTableModel tblModel = (javax.swing.table.DefaultTableModel) tableBeli.getModel();
        if (tableBeli.getSelectedRowCount() == 1) {
            int status = javax.swing.JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus?", "DELETE", javax.swing.JOptionPane.YES_NO_OPTION);
            if (status == 0) {
//                HAPUS
                tblModel.removeRow(tableBeli.getSelectedRow());
                javax.swing.JOptionPane.showMessageDialog(null, "Data telah dihapus", "DELETE", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
//                SET ALL DEFAULT VALUES
                namaBarang.setSelectedIndex(-1);
                hargaBeli.setText("");
                hargaJual.setText("");
                jumlah.setText("");
                
//                UPDATE HARGA DAN TOTAL HARGA
                updateHarga();
                
                javax.swing.JOptionPane.showMessageDialog(null, "SUCCESS DELETING", "SUCCESS", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Pilih satu row", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void beliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliButtonActionPerformed
        int totalHargaTemp = Integer.parseInt(totalHarga.getText());
        if (totalHargaTemp == 0){
            javax.swing.JOptionPane.showMessageDialog(null, "Tidak ada pembelian", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int status = javax.swing.JOptionPane.showConfirmDialog(null, "Sudah yakin dengan datanya?", "Confirm Submission", javax.swing.JOptionPane.YES_NO_OPTION);
        if (status == 0) {
//        GET ALL FIELD
            String namaSuppString = namaSupp.getSelectedItem().toString();
            String nomorNotaString = nomorNota.getText();
            String tanggalNotaString = tanggalNota.getSelectedItem().toString();
            javax.swing.table.DefaultTableModel tblModel = (javax.swing.table.DefaultTableModel) tableBeli.getModel();

            
//        CARI ID NAMA SUPPLIER
            int id = 0;
            try (java.util.Scanner scan = new java.util.Scanner(namaSuppString);
                    java.sql.Statement stmt = cons.createStatement())
            {
                scan.useDelimiter("/");
                String nama = scan.next();
                String kota;
                try {
                    kota = scan.next();
                    if (kota == null)
                        throw new java.util.NoSuchElementException();
                    
                    java.sql.ResultSet resultSet = stmt.executeQuery("SELECT id FROM client WHERE "
                            + "nama_client = '" + nama + "' AND kota_client = '" + kota + "'");
                    while (resultSet.next()) {
                        id = resultSet.getInt("id");
                    }
                    
                } catch (java.util.NoSuchElementException ex) {
                    java.sql.ResultSet resultSet = stmt.executeQuery("SELECT id FROM client WHERE "
                            + "nama_client = '" + nama + "' AND kota_client IS NULL");
                    while (resultSet.next()) {
                        id = resultSet.getInt("id");
                    }
                }
                
            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Gagal dapat id nama supplier", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

//        GET TODAY DATE IN SQL
            java.sql.Date sqlDate = GeneralFunction.date2SQLDate(tanggalNotaString);
            
            
//        LOOPING TABLE SAMBIL:
            for (int i = 0; i < tblModel.getRowCount(); i++) {
                String namaBarangString = tblModel.getValueAt(i, 0).toString();
                int hargaBeliInt = Integer.parseInt(tblModel.getValueAt(i, 1).toString());
                int stockInt = Integer.parseInt(tblModel.getValueAt(i, 3).toString());
                
//        TAMBAHIN STOCK DI DAFTAR STOCK DAN UPDATE HARGA BELI
                try (java.sql.PreparedStatement stmt = cons.prepareStatement("UPDATE stock SET "
                            + "stock_akhir = stock_akhir + ?, "
                            + "qty_in = qty_in + ?, "
                            + "harga_barang = ? "
                            + "WHERE nama_barang = ?")){
                    stmt.setInt(1, stockInt);
                    stmt.setInt(2, stockInt);
                    stmt.setInt(3, hargaBeliInt);
                    stmt.setString(4, namaBarangString);
                    stmt.executeUpdate();
                } catch (java.sql.SQLException e) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Gagal menambah stock " + namaBarangString, "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
                
//        MASUKIN KE database beli
                try (java.sql.PreparedStatement stmt = cons.prepareStatement("INSERT INTO beli "
                        + "(id_client, nomor_nota, tanggal_nota, nama_barang, harga_barang, qty_barang, total_harga, diskon_nota) "
                        + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)"))
                {
                    stmt.setInt(1, id);
                    stmt.setString(2, nomorNotaString);
                    stmt.setDate(3, sqlDate);
                    stmt.setString(4, namaBarangString);
                    stmt.setInt(5, hargaBeliInt);
                    stmt.setInt(6, stockInt);
                    stmt.setInt(7, hargaBeliInt * stockInt);
                    stmt.setDouble(8, Double.parseDouble(diskon.getText()) / 100);
                    stmt.execute();
                } catch (java.sql.SQLException e) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Gagal insert ke table beli, nama_barang: " + namaBarangString, "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
                }

            }
//        SELESAI LOOPING

//        MASUKIN KE bnota
            try (java.sql.PreparedStatement stmt = cons.prepareStatement("INSERT INTO bnota "
                    + "(id_client, nomor_nota, tanggal_nota, nilai_nota, diskon_nota, lunas_nota, diskon_lunas, saldo_nota) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)"))
            {
                stmt.setInt(1, id);
                stmt.setString(2, nomorNotaString);
                stmt.setDate(3, sqlDate);
                stmt.setInt(4, Integer.parseInt(totalHarga.getText()));
                stmt.setDouble(5, Double.parseDouble(diskon.getText()) / 100);
                stmt.setInt(6, 0);
                stmt.setDouble(7, 0);
                stmt.setInt(8, Integer.parseInt(totalHarga.getText()));
                stmt.execute();
            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Gagal insert ke table bnota", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
            
//        TAMBAHIN SLDAKHIR_UTANG client
            try (java.sql.PreparedStatement stmt = cons.prepareStatement("UPDATE client "
                    + "SET sldakhir_utang = sldakhir_utang + ? "
                    + "WHERE id = ?"))
            {
                stmt.setInt(1, Integer.parseInt(totalHarga.getText()));
                stmt.setInt(2, id);
                stmt.executeUpdate();
            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Gagal menambahkan saldo utang", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

//        SUCCESS MESSAGE & REDIRECT
            javax.swing.JOptionPane.showMessageDialog(null, "SUCCESS BELI BARANG", "SUCCESS", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            dispose();
            new com.sa.cobacoba.MainWindow().setVisible(true);
        }
    }//GEN-LAST:event_beliButtonActionPerformed

    private void namaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaBarangActionPerformed
        String namaBarangString;
        try {
            namaBarangString = namaBarang.getSelectedItem().toString();
        } catch (java.lang.NullPointerException e) {
            return;
        }
        
        try (java.sql.PreparedStatement stmt = cons.prepareStatement("SELECT * FROM stock WHERE nama_barang = ?")) {
            stmt.setString(1, namaBarangString);
            java.sql.ResultSet resultSet = stmt.executeQuery();
            while (resultSet.next()) {
                hargaBeli.setText(String.valueOf(resultSet.getInt("harga_barang")));
                hargaJual.setText(String.valueOf(resultSet.getInt("jual_barang")));
            }
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error querying nama_barang in database", "ERROR", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_namaBarangActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        boolean salah = validateForm();
        if (!salah) {
            String namaBarangString = namaBarang.getSelectedItem().toString();
            int stockInt = Integer.parseInt(jumlah.getText());
            String hargaBeliString = hargaBeli.getText();
            String hargaJualString = hargaJual.getText();
            
            javax.swing.table.DefaultTableModel tblModel = (javax.swing.table.DefaultTableModel) tableBeli.getModel();

//            MASUKIN KE TABLE
            String[] data = {namaBarangString, hargaBeliString, hargaJualString, String.valueOf(stockInt)};
            tblModel.addRow(data);
            
//            SET ALL DEFAULT VALUES
            namaBarang.setSelectedIndex(-1);
            hargaBeli.setText("");
            hargaJual.setText("");
            jumlah.setText("");
            
//            UPDATE HARGA
            updateHarga();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void tableBeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBeliMouseClicked
        javax.swing.table.DefaultTableModel tblModel = (javax.swing.table.DefaultTableModel) tableBeli.getModel();
        
        String namaString = tblModel.getValueAt(tableBeli.getSelectedRow(), 0).toString();
        String hargaBeliString = tblModel.getValueAt(tableBeli.getSelectedRow(), 1).toString();
        String hargaJualString = tblModel.getValueAt(tableBeli.getSelectedRow(), 2).toString();
        String jumlahString = tblModel.getValueAt(tableBeli.getSelectedRow(), 3).toString();
        
        namaBarang.setSelectedItem(namaString);
        hargaBeli.setText(hargaBeliString);
        hargaJual.setText(hargaJualString);
        jumlah.setText(jumlahString);
    }//GEN-LAST:event_tableBeliMouseClicked

    private void diskonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diskonKeyReleased
        try {
            long hargaTotalLong = Long.parseLong(harga.getText());
            double diskonLong = Double.parseDouble(diskon.getText()) / 100;
            if (diskon.getText().isEmpty()) {
                throw new java.lang.NullPointerException();
            }
            long totalHargaDiskonLong = hargaTotalLong - Math.round(hargaTotalLong * diskonLong);
            totalHarga.setText(String.valueOf(totalHargaDiskonLong));
            beliButton.setEnabled(true);
        } catch (java.lang.NullPointerException | java.lang.NumberFormatException e) {
            beliButton.setEnabled(false);
        }
    }//GEN-LAST:event_diskonKeyReleased
    
    private boolean validateForm() {
        try {
            String namaBarangString = namaBarang.getSelectedItem().toString();
            
            if (namaBarangString.isEmpty()) {
                throw new java.lang.NullPointerException("Nama barang kosong");
            }
            
            if (jumlah.getText().isEmpty()) {
                throw new java.lang.NullPointerException("Jumlahnya kosong");
            }
            Integer.parseInt(jumlah.getText());
            
            if (hargaBeli.getText().isEmpty()) {
                throw new java.lang.NullPointerException("Harga Beli kosong");
            }
            Integer.parseInt(hargaBeli.getText());
            
            if (hargaJual.getText().isEmpty()) {
                throw new java.lang.NullPointerException("Harga Jual kosong");
            }
            Integer.parseInt(hargaJual.getText());
        } catch (java.lang.NullPointerException | java.lang.NumberFormatException e) {
            peringatan.setText(e.getMessage());
            peringatan.setVisible(true);
            javax.swing.Timer timer = new javax.swing.Timer(5000, e2 -> peringatan.setVisible(false));
            timer.setRepeats(false);
            timer.start();
            return true;
        }
        return false;
    }
    
    private void updateHarga() {
        long hargaTotalLong = 0;
        javax.swing.table.DefaultTableModel tblModel = (javax.swing.table.DefaultTableModel) tableBeli.getModel();
        if (tblModel.getRowCount() == 0) {
            harga.setText("0");
            totalHarga.setText("0");
            return;
        }
        
        for (int i = 0; i < tblModel.getRowCount(); i++) {
            long hargaLong = Long.parseLong(tblModel.getValueAt(i, 2).toString());
            long qty = Long.parseLong(tblModel.getValueAt(i, 3).toString());
            hargaTotalLong += hargaLong * qty;
        }
        harga.setText(String.valueOf(hargaTotalLong));
        double diskonLong = Double.parseDouble(diskon.getText()) / 100;
        long totalHargaDiskonLong = hargaTotalLong - Math.round(hargaTotalLong * diskonLong);
        totalHarga.setText(String.valueOf(totalHargaDiskonLong));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton beliButton;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField diskon;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField hargaBeli;
    private javax.swing.JTextField hargaJual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JComboBox<String> namaBarang;
    private javax.swing.JComboBox<String> namaSupp;
    private javax.swing.JTextField nomorNota;
    private javax.swing.JLabel peringatan;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton submitButton;
    private javax.swing.JTable tableBeli;
    private javax.swing.JComboBox<String> tanggalNota;
    private javax.swing.JTextField totalHarga;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
