/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sa.cobacoba.edit;

/**
 *
 * @author jasonevan
 */
public class EditWindow extends javax.swing.JFrame {

    java.sql.Connection cons;
    public EditWindow(java.sql.Connection conn) {
        cons = conn;
        initComponents();
        
        EditPenjualan edit = new EditPenjualan(cons, this, jMenu1, jMenu2, jMenu3, jMenu4);
        jPanel2.add(edit, java.awt.BorderLayout.CENTER);
        jPanel2.revalidate();
        jPanel2.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        editPenjualan = new javax.swing.JMenuItem();
        editPembelian = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        editUtang = new javax.swing.JMenuItem();
        editPiutang = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        returPenjualan = new javax.swing.JMenuItem();
        returPembelian = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        editClient = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(1350, 750));
        jPanel2.setPreferredSize(new java.awt.Dimension(1350, 750));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jMenuBar1.setMinimumSize(new java.awt.Dimension(75, 35));
        jMenuBar1.setOpaque(false);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(75, 35));

        jMenu1.setText("Transaksi");

        editPenjualan.setText("Penjualan");
        editPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPenjualanActionPerformed(evt);
            }
        });
        jMenu1.add(editPenjualan);

        editPembelian.setText("Pembelian");
        editPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPembelianActionPerformed(evt);
            }
        });
        jMenu1.add(editPembelian);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pelunasan");

        editUtang.setText("Utang");
        editUtang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUtangActionPerformed(evt);
            }
        });
        jMenu2.add(editUtang);

        editPiutang.setText("Piutang");
        editPiutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPiutangActionPerformed(evt);
            }
        });
        jMenu2.add(editPiutang);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Retur");

        returPenjualan.setText("Retur Penjualan");
        returPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returPenjualanActionPerformed(evt);
            }
        });
        jMenu3.add(returPenjualan);

        returPembelian.setText("Retur Pembelian");
        returPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returPembelianActionPerformed(evt);
            }
        });
        jMenu3.add(returPembelian);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Daftar");

        editClient.setText("Client");
        jMenu4.add(editClient);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPenjualanActionPerformed
        EditPenjualan edit = new EditPenjualan(cons, this, jMenu1, jMenu2, jMenu3, jMenu4);
        
        jPanel2.removeAll();
        jPanel2.add(edit, java.awt.BorderLayout.CENTER);
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_editPenjualanActionPerformed

    private void editPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPembelianActionPerformed
        EditPembelian edit = new EditPembelian(cons, this, jMenu1, jMenu2, jMenu3, jMenu4);
        
        jPanel2.removeAll();
        jPanel2.add(edit, java.awt.BorderLayout.CENTER);
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_editPembelianActionPerformed

    private void editUtangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUtangActionPerformed
        EditUtang edit = new EditUtang(cons, this, jMenu1, jMenu2, jMenu3, jMenu4);
        
        jPanel2.removeAll();
        jPanel2.add(edit, java.awt.BorderLayout.CENTER);
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_editUtangActionPerformed

    private void editPiutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPiutangActionPerformed
        EditPiutang edit = new EditPiutang(cons, this, jMenu1, jMenu2, jMenu3, jMenu4);
        
        jPanel2.removeAll();
        jPanel2.add(edit, java.awt.BorderLayout.CENTER);
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_editPiutangActionPerformed

    private void returPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returPenjualanActionPerformed
        EditReturPenjualan retur = new EditReturPenjualan(cons, this, jMenu1, jMenu2, jMenu3, jMenu4);
        
        jPanel2.removeAll();
        jPanel2.add(retur, java.awt.BorderLayout.CENTER);
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_returPenjualanActionPerformed

    private void returPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returPembelianActionPerformed
        EditReturPembelian retur = new EditReturPembelian(cons, this, jMenu1, jMenu2, jMenu3, jMenu4);
        
        jPanel2.removeAll();
        jPanel2.add(retur, java.awt.BorderLayout.CENTER);
        jPanel2.revalidate();
        jPanel2.repaint();
    }//GEN-LAST:event_returPembelianActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem editClient;
    private javax.swing.JMenuItem editPembelian;
    private javax.swing.JMenuItem editPenjualan;
    private javax.swing.JMenuItem editPiutang;
    private javax.swing.JMenuItem editUtang;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem returPembelian;
    private javax.swing.JMenuItem returPenjualan;
    // End of variables declaration//GEN-END:variables
}
