/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sa.cobacoba.retur;

/**
 *
 * @author jasonevan
 */
public class ReturWindow extends javax.swing.JFrame {

    java.sql.Connection cons;
    public ReturWindow(java.sql.Connection conn) {
        cons = conn;
        initComponents();
        ReturPenjualan penjualan = new ReturPenjualan(cons, this);
        dataPanel.add(penjualan, java.awt.BorderLayout.CENTER);
        dataPanel.revalidate();
        dataPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        penjualanMenu = new javax.swing.JMenu();
        pembelianMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 705));
        setPreferredSize(new java.awt.Dimension(1350, 705));

        dataPanel.setBackground(new java.awt.Color(51, 51, 51));
        dataPanel.setMinimumSize(new java.awt.Dimension(1350, 665));
        dataPanel.setPreferredSize(new java.awt.Dimension(1350, 665));
        dataPanel.setLayout(new java.awt.BorderLayout());

        jMenuBar1.setPreferredSize(new java.awt.Dimension(75, 30));

        penjualanMenu.setText("Penjualan");
        penjualanMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(penjualanMenu);

        pembelianMenu.setText("Pembelian");
        pembelianMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pembelianMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(pembelianMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void penjualanMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanMenuActionPerformed
        ReturPenjualan penjualan = new ReturPenjualan(cons, this);
        dataPanel.removeAll();
        dataPanel.add(penjualan, java.awt.BorderLayout.CENTER);
        dataPanel.revalidate();
        dataPanel.repaint();
    }//GEN-LAST:event_penjualanMenuActionPerformed

    private void pembelianMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembelianMenuMouseClicked
        ReturPembelian pembelian = new ReturPembelian(cons, this);
        dataPanel.removeAll();
        dataPanel.add(pembelian, java.awt.BorderLayout.CENTER);
        dataPanel.revalidate();
        dataPanel.repaint();
    }//GEN-LAST:event_pembelianMenuMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dataPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu pembelianMenu;
    private javax.swing.JMenu penjualanMenu;
    // End of variables declaration//GEN-END:variables
}
